### ISSUE TITLE
KWin debug?

### ISSUE THREAD

**Issue by bam80** [wmww/wayland-debug#33]
Hi, thanks for the tool!
I wonder if KWin itself could also be debugged with it?

**Comment by wmww** [comment]
Does it use libwayland? Then probably yes. Other compositors (Mir and wlroots) run fine in it. You'll almost certainly need to run in gdb mode due to #5.

**Comment by bam80** [comment]
Oh, cool!
(just saw it is actually mentioned in [Readme](https://github.com/wmww/wayland-debug#wayland-debug) :)
