### ISSUE TITLE
Add the project to Freedesktop's Wayland debugging utility list

### ISSUE THREAD

**Issue by Jaakkonen** [wmww/wayland-debug#50]
Freedesktop keeps track of debugging utilities at https://wayland.freedesktop.org/extras.html and it'd be nice to have this tool listed there.
It looks like that a PR to https://gitlab.freedesktop.org/wayland/wayland.freedesktop.org could be made to make that happen.

**Comment by wmww** [comment]
You're more than welcome to make such a PR. I'm not going to do so because it feels somewhat like annoying self-promoting, but if other people fine my tool useful than please spread the word!
